import "../globals.css";
export const metadata = {
  title: "test site",
  description: "Generated by next and sanity",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
